version: '3.9'
services:
    app1:
        restart: always
        build: ./top_songs_app
        ports:
            - "80:5000"
        
    app2:
        restart: always
        build: ./browser
        ports:
            - "443:5000"