version: '3.9'
services:
    app1:
        restart: always
        build: ./top_songs_app
        ports:
            - "5000:5000"
        
    app2:
        restart: always
        build: ./browser
        ports:
            - "3000:5000"