version: '3.9'
services:
    web-app:
        build: .
        ports:
            - "5000:5000"
    mysqldb:
        image: mysql:latest
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=p@ssword1